### ISSUE TITLE
More integration test coverage for dependency substitution

### ISSUE THREAD

**Issue by bigdaz** [prezi/gradle#12]
I think we need more coverage for replacing an external dependency with a project dependency:
- [x] Interaction with forced versions and other resolve rules
- [x] Replacement of transitive dependencies (could be added to existing test case)
- [x] Conflict resolution where 2 external dependency versions are in graph, but only one version is replaced by project dependency
- [x] Real resolution of dependency files: pre-build the substituted project. (This test would later be modified to remove the pre-build step).

**Comment by bigdaz** [comment]
More here: https://github.com/gradle/gradle/blob/master/design-docs/dependency-substitution.md#test-coverage

**Comment by lptr** [comment]
All of these should be done now.
