### ISSUE TITLE
Dependency reports provide information on dependency substitution

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#2]
This seems to work already for module -> project replacements. I seem to remember that we discussed that this story only meant that we should add explicit tests to make sure that the thing keeps working. Is there anything else?

**Comment by bigdaz** [comment]
We just need test coverage to prove this works (for substitutions in both directions). Adam indicated that this should already work, but we need to make those tests pass, of course!

**Comment by bigdaz** [comment]
I'd prefer that we use separate PRs for each story in the design spec. Makes review easier. In general, I'd prefer smaller PRs that are merged more often, but that relies on me giving prompt feedback!

**Comment by bigdaz** [comment]
I've removed the separate story for this, and just added test coverage to the 2 substitution stories.
