### ISSUE TITLE
Merge IDE plugins test PR

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#21]
Can be merged, but will need updating after the other PRs, as it uses `ResolutionStrategy.eachDependency()` in the tests.

See https://github.com/gradle/gradle/pull/411

Should we merge this, or wait?

**Comment by bigdaz** [comment]
I'm happy to merge, and fix the tests later. On it now.

**Comment by bigdaz** [comment]
This PR has been merged. I'll add another issue for the replacement of a transitive external dependency with a project dependency, which seems to be failing. (Or possibly I've screwed up the test implementation).
