### ISSUE TITLE
DefaultDependencyResolveDetails stores old ModuleVersionSelector

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#4]
We decided to give DDRD both the component selector and the module version selector, so that we can easily return the module version selector for the deprecated API — https://github.com/prezi/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/DefaultDependencyResolveDetails.java#L34-34

Is this okay?

**Comment by bigdaz** [comment]
Looks fine to me
