### ISSUE TITLE
Final design for DependencyResolveDetails

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#8]
``` java
@Incubating
public interface DependencyResolveDetails<T extends ComponentSelector> {

    T getSelector();

    @Deprecated
    ModuleVersionSelector getRequested();

    void useTarget(Object notation);

    @Deprecated
    void useVersion(String version);
}
```

Does this look like a good way to do this?

**Comment by bigdaz** [comment]
I think this is ok for now, and we should revisit before the next release:

Questions:
- Do we want to deprecate `useVersion`?
- `getRequested` is probably a better name than `getSelector`. Just change the return type?

**Comment by bigdaz** [comment]
We'll also want to use `DeprecationLogger` to nag users about use of deprecated methods. I'd leave this until we finalise on the deprecation plan.

**Comment by lptr** [comment]
If we simply change the return type of `getRequested()`, it will break old builds, because `ModuleVersionSelector` has a `getName()`, but `ModuleComponentSelector` has a `getModule()`, so this won't work anymore:

``` groovy
if (details.requested.name == "guava") { /* ... */ }
```

**Comment by lptr** [comment]
I'm not sure about `useVersion()` -- it only makes sense when you are replacing a module component. And if you have something like Pride in your build, you can "accidentally" get a project component, and you'd end up with an error.

**Comment by bigdaz** [comment]
Let's defer this discussion and propose the new API on the dev list when it's stabilised. 

An option for `getRequested()` would be to return an extended ModuleComponentSelector with a 'name' method, and issue a deprecation warning when it is used, suggesting change to 'module.

**Comment by lptr** [comment]
I like this approach. Would you introduce a special `ModuleComponentSelector` subclass for this, or would you add `getName()` to `ModuleComponentSelector` itself? I think the latter would be sufficient, and a much simpler solution.

**Comment by bigdaz** [comment]
I'm thinking that maybe we'd even add it to the implementation `DefaultModuleComponentSelector`, and not to the interface. It would then still be accessible via Groovy, but not visible in the Java API. Otherwise just add it to `ModuleComponentSelector`.  I wouldn't bother introducing a new subtype just for this.

It's not a big deal, because the plan would be to deprecate it immediately and remove it as soon as we branch for Gradle 2.4.

**Comment by bigdaz** [comment]
As discussed on the dev list, I think we should go with a deprecate-and-replace approach. This means that we won't modify DependencyResolveDetails at all.

**Comment by lptr** [comment]
This is now taken care of in https://github.com/gradle/gradle/pull/417
