### ISSUE TITLE
Accepting the pull-request

### ISSUE THREAD

**Issue by lptr** [prezi/gradle#9]
What do we need to merge back to Gradle master? Can we catch the 2.4 release train?

**Comment by bigdaz** [comment]
Shouldn't be a problem to get into 2.4, we won't start planning until we've got 2.3 final out of the way.

In order to merge, we just need to ensure that all tests are passing and that there's nothing glaringly bad in the implementation. We don't need to wait for the solution to be complete before merging.

**Comment by lptr** [comment]
Our tests are running now: https://travis-ci.org/prezi/gradle

There are only two questions we have to sort out before we can merge the current master of the fork now:
- https://github.com/prezi/gradle/blob/master/subprojects/diagnostics/src/main/groovy/org/gradle/api/tasks/diagnostics/internal/graph/nodes/UnresolvedDependencyEdge.java#L35-35 -- this is related to #7
- https://github.com/prezi/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultDependencyMetaData.java#L131-131 -- this is related to #5

Can you help sort these issues out quick? We'd need to get this merged in in order to start with the other pull-requests for the rest of the stories.

**Comment by bigdaz** [comment]
The Travis-CI build is not sufficient, as it doesn't run all of the integration tests, I don't think.

For the changes you're making, it would be important to run `./gradlew quickCheck :dependencyManagement:check` at the very least.

**Comment by bigdaz** [comment]
In order to make things easier to merge & review, it would be good if the commits could be combined somewhat and rebased to master. Removing some of the noise will make it simpler, I think.

**Comment by lptr** [comment]
I've cleaned things up somewhat, and created a pull-request: https://github.com/gradle/gradle/pull/398

**Comment by bigdaz** [comment]
OK I've made a bunch of comments on the first commit. Most of the changes are pretty minor, and most can be done post-merge.

I'll probably try to merge tomorrow: I'll do some work to remove the 2 ProjectDependencyMetaData types if you guys don't get to it by then.

**Comment by bigdaz** [comment]
PR merged
